# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  build:
    desc: Builds the site from constituent parts
    cmds:  
      - go run .
  serve:
    desc: Serves the site locally (with no auto-updating)
    cmds:
      - serve -port 8081 dist/
  dev:
    desc: Allows for local development, rerunning `task build` when changes are spotted
    cmds:
      - task serve & find {*.tmpl,static,*.go} -type f | entr -cc task build
  postcards:
    desc: Pulls postcards from `ORIGINAL_POSTCARDS` (as specified in `.env`)
    cmds:
      - /Users/jp/src/personal/dotpostcard/dist/postcards_darwin_arm64_v8.0/postcards -f web --remove-border --out-dir ./postcards "${ORIGINAL_POSTCARDS}"/*
