# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  build:
    cmds:  
      - go run .
  serve:
    cmds:
      - serve -n dist/
  dev:
    cmds:
      - task serve & find {*.tmpl,static,*.go} -type f | entr -cc task build
  postcards:
    cmds:
      - for y in "${ORIGINAL_POSTCARDS}"/*.yaml; do postcards compile --outdir ./postcards --web --override "$y"; done
